# Generated by Django 6.0.6 on 2026-07-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuing_body', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('validity_months', models.PositiveIntegerField(blank=True, help_text='Leave blank if certification never expires', null=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'issuing_body')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certs/%Y/%m/')),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='certifications.certification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employees.employee')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
