# Generated by Django 6.0.6 on 2026-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='cert_templates/'),
        ),
    ]
