# Generated by Django 6.0.6 on 2026-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('cert_expiry', 'Certification Expiry'), ('new_cert', 'New Certification Logged'), ('training_required', 'Training Required'), ('training_reminder', 'Training Reminder'), ('skill_gap', 'Skill Gap'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
