# Generated by Django 6.0.6 on 2026-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingenrollment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending_approval', max_length=20),
        ),
    ]
