# Generated by Django 6.0.6 on 2026-07-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_profileupdaterequest'),
        ('training', '0002_alter_trainingenrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='employees.department'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
