# Generated by Django 6.0.6 on 2026-07-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=150)),
                ('readiness', models.CharField(choices=[('ready_now', 'Ready Now'), ('1_year', '1 Year'), ('2_years', '2+ Years')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_candidacies', to='employees.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_plans', to='employees.department')),
                ('incumbent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succession_incumbencies', to='employees.employee')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='succession_plans', to='skills.skill')),
            ],
            options={
                'ordering': ['target_role', 'readiness'],
            },
        ),
    ]
