# Generated by Django 6.0.6 on 2026-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_accepted_consent',
            field=models.BooleanField(default=False),
        ),
    ]
