# Generated by Django 6.0.6 on 2026-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_profileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='chronic_illnesses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='guardian_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
