# Generated by Django 6.0.6 on 2026-07-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_allergies_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='guardian_name',
            new_name='next_of_kin_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='guardian_contact',
            new_name='next_of_kin_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='guardian_type',
            new_name='next_of_kin_relationship',
        ),
    ]
