# Generated by Django 6.0.6 on 2026-07-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_job_title_employee_employment_status_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
        migrations.AlterField(
            model_name='skillsassessment',
            name='resulting_proficiency',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], null=True),
        ),
        migrations.CreateModel(
            name='PositionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')])),
                ('is_critical', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_competencies', to='employees.position')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_positions', to='skills.skill')),
            ],
            options={
                'ordering': ['position', '-required_level'],
                'unique_together': {('position', 'skill')},
            },
        ),
    ]
