# Generated by Django 6.0.6 on 2026-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_employeeskill_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
