# Generated by Django 6.0.6 on 2026-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskill',
            name='confidence_score',
            field=models.IntegerField(default=75, help_text='Skill confidence percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='verification_status',
            field=models.CharField(choices=[('self_assessed', 'Self Assessed'), ('manager_verified', 'Manager Verified'), ('ai_validated', 'AI Validated')], default='self_assessed', max_length=20),
        ),
    ]
